selectedProfileId = '925A4807-AA0C-46A1-8213-A08782DE3445'

[[profiles]]
id = '925A4807-AA0C-46A1-8213-A08782DE3445'
name = 'Default'

[[profiles.workspaces]]
assignAppShortcut = 'cmd+opt+shift+a'
display = 'Built-in Retina Display'
id = '678B1EF0-1054-474D-BBAE-2A0F2BEA6E2D'
name = 'Side-Monitor'
shortcut = 'cmd+ctrl+opt+shift+a'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.google.Chrome'
iconPath = '/Applications/Google Chrome.app/Contents/Resources/app.icns'
name = 'Google Chrome'

[[profiles.workspaces]]
assignAppShortcut = 'cmd+opt+shift+s'
display = 'U28E590'
id = 'F6FCB988-63A3-462C-BBA3-A23FDB3D6EC6'
name = 'Browser'
shortcut = 'cmd+ctrl+opt+shift+s'
symbolIconName = 'globe'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.google.Chrome'
iconPath = '/Applications/Google Chrome.app/Contents/Resources/app.icns'
name = 'Google Chrome'

[[profiles.workspaces]]
assignAppShortcut = 'cmd+opt+shift+d'
display = 'U28E590'
id = 'BCB67D72-4467-4CDC-80CA-1E7ABD31A4FA'
name = 'Development'
shortcut = 'cmd+ctrl+opt+shift+d'
symbolIconName = 'desktopcomputer'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.mitchellh.ghostty'
iconPath = '/Applications/Ghostty.app/Contents/Resources/AppIcon.icns'
name = 'Ghostty'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.todesktop.230313mzl4w4u92'
iconPath = '/Applications/Cursor.app/Contents/Resources/icon.icns'
name = 'Cursor'

[[profiles.workspaces.apps]]
bundleIdentifier = 'dev.zed.Zed'
iconPath = '/Applications/Zed.app/Contents/Resources/Zed.icns'
name = 'Zed'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.microsoft.VSCode'
iconPath = '/Applications/Visual Studio Code.app/Contents/Resources/Code.icns'
name = 'Code'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.culturedcode.ThingsMac'
iconPath = '/Applications/Things3.app/Contents/Resources/App-Release.icns'
name = 'Things'

[[profiles.workspaces]]
assignAppShortcut = 'cmd+opt+shift+f'
display = 'U28E590'
id = '513673CF-0D6F-48A2-B0F2-69AD333505BD'
name = 'Non-Focus'
shortcut = 'cmd+ctrl+opt+shift+f'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.apple.mail'
iconPath = '/System/Applications/Mail.app/Contents/Resources/ApplicationIcon.icns'
name = 'Mail'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.apple.iCal'
iconPath = '/System/Applications/Calendar.app/Contents/Resources/AppIcon.icns'
name = 'Calendar'