checkForUpdatesAutomatically: false
showMenuBarTitle: false
menuBarTitleTemplate: $WORKSPACE
menuBarDisplayAliases: ''
enableFocusManagement: true
centerCursorOnFocusChange: false
focusLeft: cmd+ctrl+opt+shift+h
focusRight: cmd+ctrl+opt+shift+l
focusUp: cmd+ctrl+opt+shift+k
focusDown: cmd+ctrl+opt+shift+j
focusNextWorkspaceApp: cmd+ctrl+opt+shift+up
focusPreviousWorkspaceApp: cmd+ctrl+opt+shift+down
focusNextWorkspaceWindow: cmd+ctrl+opt+shift+left
focusPreviousWorkspaceWindow: cmd+ctrl+opt+shift+right
centerCursorOnWorkspaceChange: true
switchToRecentWorkspace: cmd+ctrl+opt+shift+tab
showFloatingNotifications: true
changeWorkspaceOnAppAssign: true
enablePictureInPictureSupport: true
floatingApps: []
floatTheFocusedApp: cmd+ctrl+opt+shift+t
unfloatTheFocusedApp: cmd+ctrl+opt+shift+r
enableSpaceControl: true
showSpaceControl: cmd+ctrl+opt+shift+g
enableSpaceControlAnimations: false
spaceControlCurrentDisplayWorkspaces: false
enableIntegrations: false
runScriptOnWorkspaceChange: ''
runScriptOnLaunch: ''
runScriptOnProfileChange: ''
