centerCursorOnFocusChange = false
centerCursorOnWorkspaceChange = true
changeWorkspaceOnAppAssign = true
checkForUpdatesAutomatically = false
enableFocusManagement = true
enableIntegrations = false
enablePictureInPictureSupport = true
enableSpaceControl = true
enableSpaceControlAnimations = false
focusDown = 'cmd+ctrl+opt+shift+j'
focusLeft = 'cmd+ctrl+opt+shift+h'
focusRight = 'cmd+ctrl+opt+shift+l'
focusUp = 'cmd+ctrl+opt+shift+k'
menuBarDisplayAliases = ''
menuBarTitleTemplate = '$WORKSPACE'
runScriptOnLaunch = ''
runScriptOnProfileChange = ''
runScriptOnWorkspaceChange = ''
showFloatingNotifications = true
showMenuBarTitle = false
showSpaceControl = 'cmd+ctrl+opt+shift+g'
spaceControlCurrentDisplayWorkspaces = false
spaceControlMaxColumns = 6
switchToRecentWorkspace = 'cmd+ctrl+opt+shift+tab'
toggleTheFocusedAppFloating = 'cmd+ctrl+opt+shift+t'

[[floatingApps]]
bundleIdentifier = 'md.obsidian'
iconPath = '/Applications/Obsidian.app/Contents/Resources/icon.icns'
name = 'Obsidian'

[[floatingApps]]
bundleIdentifier = 'com.electron.min'
iconPath = '/Applications/Min.app/Contents/Resources/icon.icns'
name = 'Min'